version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

