version: "3.8"
services:
  backend:
    build: ./backend
    container_name: cetpredictor_backend
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: cetpredictor_frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/docker-certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
 
