version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://3.89.226.241:5000   # Set this in frontend/pages/index.js also!
    depends_on:
      - backend

